'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3625
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



Partial Public Class agregarResto

    '''<summary>
    '''RestoNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RestoNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RestoName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RestoName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RestoNameRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RestoNameRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''DireccionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DireccionLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Direccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Direccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TelefonoLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TelefonoLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Telefono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Telefono As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnAgregarResto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAgregarResto As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As webAppResto.MasterPage
        Get
            Return CType(MyBase.Master, webAppResto.MasterPage)
        End Get
    End Property
End Class
